FROM luafan/luafan-ubuntu:local_base

ENV LUAFAN_VERSION=0.7-3

COPY . /root/luafan/
RUN cd /root/luafan \
    && CFLAGS="-g -O2" \
       luarocks make luafan-$LUAFAN_VERSION.rockspec \
       MARIADB_DIR=/usr/local/mysql \
       CURL_INCDIR=/usr/include/$(uname -m)-linux-gnu \
    && cd .. && rm -rf luafan
