name: LuaFan CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-alpine:
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.16.9

    steps:
    - name: Install git
      run: apk add --update git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LuaFan (Alpine)
      run: |
        cd $GITHUB_WORKSPACE
        sh build_docker_alpine.sh || exit -1

    - name: Build completion
      run: echo "Build Alpine finished!"

  build-ubuntu:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04

    steps:
    - name: Install git
      run: apt update && apt install -y git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LuaFan (Ubuntu)
      run: |
        cd $GITHUB_WORKSPACE
        bash build_docker_ubuntu.sh || exit -1

    - name: Build completion
      run: echo "Build Ubuntu finished!"

  # Additional job for running tests using our comprehensive test suite
  test-comprehensive:
    runs-on: ubuntu-22.04
    needs: [build-ubuntu]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake pkg-config \
          liblua5.3-dev libssl-dev libcurl4-openssl-dev \
          libevent-dev libmariadb-dev lua5.3

    - name: Build for testing
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        make -j$(nproc)

    - name: Run comprehensive tests
      run: |
        cd tests
        chmod +x run_all_tests.sh
        ./run_all_tests.sh --verbose